export const regexps = {
 next: [/_next/],
 googlefonts: [/font.googleapis/, /fonts.gstatic/],
 tailwindcss: [/MIT License | https:\/\/tailwindcss.com/, /--tw-/],
 lenis: [/lenis/],
 cloudinary: [/res.cloudinary.com/],
 fontawesome: [/\/fontawesome/],
 vue: [/vue/],
 react: [/https:\/\/reactjs.org\/docs\/error-decoder.html/, /react.forward_ref/, /__reactInternal/],
 sveltekit: [/data-sveltekit/, /x-sveltekit-/],
 svelte: [/window.__svelte/, /svelte-announcer/],
 nuxt: [/_nuxt/, /window.__NUXT__/],
 preact: [/preact/],
 cloudflareanalytics: [/static.cloudflareinsights.com/],
 webpack: [/window.webpackJsonp/, /__webpack_require__/, /__webpack_module_/, /__webpack_exports__/],
 jquery: [/jquery.org\/license/, /jquery-migrate/, /jquery.*(js)/],
 bootstrap: [/bootstrapcdn.com/, /http:\/\/getbootstrap.com/],
} as const;

export default {
 cloudflareanalytics: { name: 'Cloudflare Browser Insights' },
 cloudinary: { name: 'Cloudinary' },
 fontawesome: { name: 'Font Awesome' },
 googlefonts: { name: 'Google Fonts' },
 lenis: { name: 'Lenis Scroll' },
 next: { name: 'Next.js' },
 nuxt: { name: 'Nuxt.js' },
 preact: { name: 'Preact' },
 react: { name: 'React' },
 svelte: { name: 'Svelte' },
 sveltekit: { name: 'SvelteKit' },
 tailwindcss: { name: 'Tailwind CSS' },
 vue: { name: 'Vue.js' },
 webpack: { name: 'Webpack' },
} as Record<keyof typeof regexps, { name: string; icon?: string }>;
